import React,{useEffect,useId} from 'react';
import {View} from 'react-native';
import Svg,{Path,Defs,RadialGradient,Stop,Text as SVGText} from 'react-native-svg';
import Animated,{useSharedValue,useAnimatedProps,withTiming,useReducedMotion} from 'react-native-reanimated';
import type {TasteVector} from '@/types';
import {useTheme} from '@/theme';
const axes:(keyof TasteVector)[]=['effort','novelty','social','rawness','spontaneity','obscurity'];
const APath=Animated.createAnimatedComponent(Path);
function shape(v:number[],factor:number){'worklet';const points=v.map((value,i)=>{const a=i*Math.PI/3-Math.PI/2;const r=(54+Math.max(0,Math.min(100,value))*.48)*factor;return {x:140+Math.cos(a)*r,y:140+Math.sin(a)*r};});let d=`M ${points[0].x} ${points[0].y}`;for(let i=0;i<6;i++){const p0=points[(i+5)%6],p1=points[i],p2=points[(i+1)%6],p3=points[(i+2)%6];d+=` C ${p1.x+(p2.x-p0.x)*.19} ${p1.y+(p2.y-p0.y)*.19} ${p2.x-(p3.x-p1.x)*.19} ${p2.y-(p3.y-p1.y)*.19} ${p2.x} ${p2.y}`;}return d+' Z';}
export function TasteprintShape({vector,size=280,labels=false,overlay,animated=true}:{vector:TasteVector;size?:number;labels?:boolean;overlay?:TasteVector;animated?:boolean}){const{colors}=useTheme();const reduced=useReducedMotion();const values=useSharedValue(axes.map(a=>vector[a]));const id=useId().replace(/:/g,'');useEffect(()=>{values.value=withTiming(axes.map(a=>vector[a]),{duration:reduced||!animated?0:650});},[vector,animated,reduced,values]);const a=useAnimatedProps(()=>({d:shape(values.value,1)}));const b=useAnimatedProps(()=>({d:shape(values.value,.83)}));const c=useAnimatedProps(()=>({d:shape(values.value,.66)}));const d=useAnimatedProps(()=>({d:shape(values.value,.5)}));return <View accessible accessibilityRole="image" accessibilityLabel={`Tasteprint. ${axes.map(a=>`${a} ${Math.round(vector[a])} of 100`).join(', ')}`} style={{width:size,height:size,alignSelf:'center'}}><Svg width={size} height={size} viewBox="0 0 280 280"><Defs><RadialGradient id={id} cx="72%" cy="63%" r="83%"><Stop offset="0" stopColor={colors.yellow}/><Stop offset=".4" stopColor={colors.mint}/><Stop offset=".7" stopColor={colors.blue}/><Stop offset="1" stopColor={colors.lilac}/></RadialGradient></Defs><APath animatedProps={a} fill={`url(#${id})`} opacity={.16}/><APath animatedProps={b} fill={`url(#${id})`} opacity={.27}/><APath animatedProps={c} fill={`url(#${id})`} opacity={.37}/><APath animatedProps={d} fill={`url(#${id})`} opacity={.53}/>{overlay&&<Path d={shape(axes.map(a=>overlay[a]),.91)} fill={colors.accent} fillOpacity={.11} stroke={colors.accent} strokeOpacity={.45} strokeWidth={1.5}/>} {labels&&axes.map((axis,i)=>{const angle=i*Math.PI/3-Math.PI/2;return <SVGText key={axis} x={140+Math.cos(angle)*125} y={145+Math.sin(angle)*125} fontSize={10} fill={colors.textSecondary} textAnchor="middle">{axis.charAt(0).toUpperCase()+axis.slice(1)}</SVGText>;})}</Svg></View>;}
export default TasteprintShape;
