import React,{useState,type PropsWithChildren} from 'react';
import {View,Text,Pressable,ScrollView,TextInput,StyleSheet,Modal,Platform,KeyboardAvoidingView,ActivityIndicator,type StyleProp,type ViewStyle,type TextStyle,type TextInputProps} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Image} from 'expo-image';
import {Feather} from '@expo/vector-icons';
import {router} from 'expo-router';
import * as Haptics from 'expo-haptics';
import {LinearGradient} from 'expo-linear-gradient';
import Animated,{useSharedValue,useAnimatedStyle,withSpring,useReducedMotion,FadeIn,FadeInDown} from 'react-native-reanimated';
import {Gesture,GestureDetector} from 'react-native-gesture-handler';
import {scheduleOnRN} from 'react-native-worklets';
import Svg,{Defs,LinearGradient as SVGGradient,Stop,Path,Polygon} from 'react-native-svg';
import {useTheme,typography,motion} from '@/theme';
import {catalog} from '@/repositories';
import type {Activity} from '@/types';
import {imageSource} from './images';

type IconName=React.ComponentProps<typeof Feather>['name'];
export function tap(){if(Platform.OS!=='web')void Haptics.selectionAsync().catch(()=>{});}
export function T({children,variant='body',color,style,numberOfLines}:PropsWithChildren<{variant?:keyof typeof typography;color?:string;style?:StyleProp<TextStyle>;numberOfLines?:number}>){const {colors}=useTheme();return <Text maxFontSizeMultiplier={1.6} numberOfLines={numberOfLines} style={[{color:color??colors.text},typography[variant],style]}>{children}</Text>;}
export function Screen({children,scroll=true,padded=true,style}:PropsWithChildren<{scroll?:boolean;padded?:boolean;style?:StyleProp<ViewStyle>}>){const {colors}=useTheme();const insets=useSafeAreaInsets();return <KeyboardAvoidingView style={[{flex:1,backgroundColor:colors.background,paddingTop:insets.top},style]} behavior={Platform.OS==='ios'?'padding':undefined}>{scroll?<ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" showsVerticalScrollIndicator={false} contentContainerStyle={{paddingHorizontal:padded?24:0,paddingTop:16,paddingBottom:Math.max(insets.bottom,20)+100,gap:24}}>{children}</ScrollView>:<View style={{flex:1,paddingHorizontal:padded?24:0,paddingTop:16,paddingBottom:Math.max(insets.bottom,20)}}>{children}</View>}</KeyboardAvoidingView>;}
export function Button({title,onPress,variant='primary',icon,disabled=false,loading=false,style}:{title:string;onPress:()=>void;variant?:'primary'|'secondary'|'ghost';icon?:IconName;disabled?:boolean;loading?:boolean;style?:StyleProp<ViewStyle>}){const{colors}=useTheme();const reduced=useReducedMotion();const scale=useSharedValue(1);const anim=useAnimatedStyle(()=>({transform:[{scale:scale.value}]}));const fg=variant==='primary'?colors.ink:colors.text;return <Animated.View style={[anim,style]}><Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityState={{disabled:disabled||loading}} disabled={disabled||loading} onPress={()=>{tap();onPress();}} onPressIn={()=>{if(!reduced)scale.value=withSpring(.98,motion.spring);}} onPressOut={()=>{scale.value=withSpring(1,motion.spring);}} style={({pressed})=>({minHeight:52,borderRadius:17,paddingHorizontal:20,paddingVertical:14,backgroundColor:variant==='primary'?(pressed?colors.accentPressed:colors.accent):variant==='secondary'?colors.surfaceAlt:'transparent',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,opacity:disabled?.4:1})}>{loading?<ActivityIndicator color={fg}/>:<>{icon&&<Feather name={icon} size={18} color={fg}/>}<T variant="label" color={fg} style={{fontSize:15}}>{title}</T></>}</Pressable></Animated.View>;}
export function IconButton({name,onPress,label,color}:{name:IconName;onPress:()=>void;label?:string;color?:string}){const{colors}=useTheme();return <Pressable accessibilityRole="button" accessibilityLabel={label??name} onPress={()=>{tap();onPress();}} style={({pressed})=>({height:44,width:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:pressed?colors.surfaceAlt:'transparent'})}><Feather name={name} size={21} color={color??colors.text}/></Pressable>;}
export function Header({title,subtitle,back=false,right}:{title?:string;subtitle?:string;back?:boolean;right?:React.ReactNode}){const{colors}=useTheme();return <View style={{gap:16}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',minHeight:44}}>{back?<IconButton name="arrow-left" label="Go back" onPress={()=>router.canGoBack()?router.back():router.replace('/(tabs)/home')}/>:<Brand size={34}/>}<View style={{flex:1}}/>{right}</View>{title&&<View style={{gap:6}}><T variant="title">{title}</T>{subtitle&&<T color={colors.textSecondary}>{subtitle}</T>}</View>}</View>;}
export function Section({title,action,onAction}:{title:string;action?:string;onAction?:()=>void}){const{colors}=useTheme();return <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12}}><T variant="heading" style={{flex:1}}>{title}</T>{action&&<Pressable accessibilityRole="button" onPress={onAction} style={{minHeight:44,justifyContent:'center'}}><T variant="small" color={colors.textSecondary}>{action}</T></Pressable>}</View>;}
export function Chip({label,selected=false,onPress,icon}:{label:string;selected?:boolean;onPress:()=>void;icon?:IconName}){const{colors}=useTheme();return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={()=>{tap();onPress();}} style={({pressed})=>({minHeight:44,borderRadius:14,paddingHorizontal:16,paddingVertical:10,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',backgroundColor:selected?colors.accentSoft:colors.surfaceAlt,borderWidth:1,borderColor:selected?colors.accent:colors.surfaceAlt,opacity:pressed?.75:1})}>{icon&&<Feather name={icon} size={16} color={selected?colors.accentPressed:colors.textSecondary}/>}<T variant="small" color={selected?colors.text:colors.textSecondary} style={{fontWeight:selected?'600':'400'}}>{label}</T>{selected&&<Feather name="check" size={14} color={colors.accentPressed}/>}</Pressable>;}
export function Field(props:TextInputProps){const{colors}=useTheme();return <TextInput accessibilityLabel={props.accessibilityLabel??props.placeholder} placeholderTextColor={colors.muted} selectionColor={colors.accent} {...props} style={[{minHeight:52,borderRadius:16,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,paddingHorizontal:16,paddingVertical:14,fontSize:16,color:colors.text},props.style]}/>;}
export function Avatar({userId='shawn',size=40}:{userId?:string;size?:number}){const{colors}=useTheme();const user=catalog.user(userId);return <View style={{width:size,height:size,borderRadius:size/2,overflow:'hidden',backgroundColor:colors.surfaceAlt,borderWidth:2,borderColor:colors.background}}><Image source={imageSource(user?.avatar??userId)} contentFit="cover" accessibilityLabel={user?.displayName??'Crew member'} style={{width:'100%',height:'100%'}}/></View>;}
export function AvatarStack({ids,size=30}:{ids:string[];size?:number}){return <View style={{flexDirection:'row',paddingRight:4}}>{ids.slice(0,5).map((id,index)=><View key={id} style={{marginLeft:index?-8:0,zIndex:5-index}}><Avatar userId={id} size={size}/></View>)}</View>;}
export function Photo({image,style,children}:PropsWithChildren<{image:string;style?:StyleProp<ViewStyle>}>){const{colors}=useTheme();const[failed,setFailed]=useState(false);return <View style={[{backgroundColor:colors.imageBase,overflow:'hidden',borderRadius:22},style]}><LinearGradient colors={[colors.mint,colors.imageBase]} style={StyleSheet.absoluteFill}/>{!failed&&<Image source={imageSource(image)} contentFit="cover" cachePolicy="memory-disk" transition={180} recyclingKey={image} onError={()=>setFailed(true)} style={StyleSheet.absoluteFill}/>}<View style={{flex:1}}>{children}</View></View>;}
export function ActivityCard({activity,compact=false,onPress,match,subtitle,meta}:{activity:Activity;compact?:boolean;onPress?:()=>void;match?:number;subtitle?:string;meta?:string}){const{colors}=useTheme();return <Pressable accessibilityRole="button" accessibilityLabel={`${activity.name}${match?`, ${match}% match`:''}`} onPress={onPress??(()=>router.push({pathname:'/activity/[id]',params:{id:activity.id}}))} style={({pressed})=>({flex:1,minWidth:0,opacity:pressed?.85:1,gap:10})}><Photo image={activity.image} style={{height:compact?124:180,borderRadius:18}}><View style={{position:'absolute',right:10,top:10,backgroundColor:colors.surface,borderRadius:20,width:29,height:29,alignItems:'center',justifyContent:'center'}}><Feather name="arrow-up-right" size={16} color={colors.text}/></View></Photo><View style={{gap:3,paddingHorizontal:2}}><T variant="label" numberOfLines={2}>{activity.name}</T><T variant="caption" color={colors.textSecondary} numberOfLines={1}>{subtitle??activity.placeName??'Wherever you are'}</T><View style={{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:5}}>{match!==undefined&&<T variant="caption" color={colors.success} style={{fontWeight:'600'}}>{match}% match</T>}<T variant="caption" color={colors.textSecondary}>{match!==undefined?'· ':''}{meta??`${activity.price===0?'Free':'$'.repeat(activity.price)} · ${activity.distance} min away`}</T></View></View></Pressable>;}
export function ActivityRow({activity,onPress,rank,subtitle,right}:{activity:Activity;onPress?:()=>void;rank?:number;subtitle?:string;right?:React.ReactNode}){const{colors}=useTheme();return <Pressable accessibilityRole="button" onPress={onPress??(()=>router.push({pathname:'/activity/[id]',params:{id:activity.id}}))} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:12,minHeight:70,padding:10,borderRadius:16,backgroundColor:pressed?colors.surfaceAlt:colors.surface})}>{rank!==undefined&&<T variant="heading" color={rank<=3?colors.accentPressed:colors.muted} style={{width:28,textAlign:'center'}}>{rank.toString().padStart(2,'0')}</T>}<Photo image={activity.image} style={{height:48,width:48,borderRadius:11}}/><View style={{flex:1,gap:2}}><T variant="label">{activity.name}</T><T variant="caption" color={colors.textSecondary}>{subtitle??activity.placeName??activity.category}</T></View>{right??<Feather name="chevron-right" size={17} color={colors.muted}/>}</Pressable>;}
export function Sheet({visible,onClose,title,children}:PropsWithChildren<{visible:boolean;onClose:()=>void;title:string}>){const{colors}=useTheme();const insets=useSafeAreaInsets();const reduced=useReducedMotion();const gesture=Gesture.Pan().onEnd(e=>{if(e.translationY>65)scheduleOnRN(onClose);});return <Modal transparent visible={visible} animationType={reduced?'fade':'slide'} onRequestClose={onClose}><View style={{flex:1,justifyContent:'flex-end',backgroundColor:colors.overlay}}><Pressable accessibilityLabel="Dismiss sheet" accessibilityRole="button" onPress={onClose} style={StyleSheet.absoluteFill}/><View accessibilityViewIsModal style={{backgroundColor:colors.background,borderTopLeftRadius:30,borderTopRightRadius:30,paddingHorizontal:24,paddingBottom:Math.max(insets.bottom,24),maxHeight:'90%',width:'100%',maxWidth:680,alignSelf:'center'}}><GestureDetector gesture={gesture}><View style={{paddingTop:12,paddingBottom:8,alignItems:'center'}}><View style={{width:36,height:4,backgroundColor:colors.border,borderRadius:3}}/></View></GestureDetector><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingBottom:16}}><T variant="heading" style={{flex:1}}>{title}</T><IconButton name="x" label="Close sheet" onPress={onClose}/></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{gap:16,paddingBottom:8}}>{children}</ScrollView></View></View></Modal>;}
export function Empty({title,body,action,onAction}:{title:string;body:string;action?:string;onAction?:()=>void}){const{colors}=useTheme();return <View style={{paddingVertical:40,gap:14,alignItems:'center'}}><View style={{width:60,height:60,borderRadius:22,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'}}><Feather name="compass" size={26} color={colors.accentPressed}/></View><T variant="heading" style={{textAlign:'center'}}>{title}</T><T color={colors.textSecondary} style={{textAlign:'center',maxWidth:300}}>{body}</T>{action&&onAction&&<Button title={action} onPress={onAction}/>}</View>;}
export function Divider(){const{colors}=useTheme();return <View style={{height:1,backgroundColor:colors.border}}/>;}
export function CubeMark({size=40}:{size?:number}){return <Svg accessibilityLabel="WTM cube" width={size} height={size} viewBox="0 0 100 100"><Defs><SVGGradient id="cubeTop" x1="0" y1="0" x2="1" y2="1"><Stop offset="0" stopColor="#FFD29B"/><Stop offset="1" stopColor="#FF806B"/></SVGGradient><SVGGradient id="cubeLeft" x1="0" y1="0" x2="1" y2="1"><Stop offset="0" stopColor="#FF8B70"/><Stop offset="1" stopColor="#F24F4D"/></SVGGradient><SVGGradient id="cubeRight" x1="0" y1="0" x2="1" y2="1"><Stop offset="0" stopColor="#FF6358"/><Stop offset="1" stopColor="#D9364D"/></SVGGradient></Defs><Polygon points="50,4 94,28 50,52 6,28" fill="url(#cubeTop)"/><Polygon points="6,28 50,52 50,98 6,74" fill="url(#cubeLeft)"/><Polygon points="50,52 94,28 94,74 50,98" fill="url(#cubeRight)"/><Path d="M50 12 L79 28 L50 44 L21 28 Z" fill="rgba(255,255,255,.18)"/></Svg>;}
export function Brand({size=40}:{size?:number}){return <View accessibilityLabel="WTM, What's the Move?" style={{flexDirection:'row',alignItems:'center',gap:8}}><CubeMark size={size}/><T variant="heading" style={{fontSize:size*.58,fontWeight:'800',letterSpacing:-.8}}>WTM</T></View>;}
export function Enter({children}:PropsWithChildren){const reduced=useReducedMotion();return <Animated.View entering={reduced?FadeIn.duration(160):FadeInDown.duration(240)}>{children}</Animated.View>;}
