import React,{useState} from 'react';
import {View,Pressable,ScrollView} from 'react-native';
import {router} from 'expo-router';
import {Feather} from '@expo/vector-icons';
import {LinearGradient} from 'expo-linear-gradient';
import {Screen,T,Avatar,AvatarStack,Brand,IconButton,Section,Photo,Button,Sheet,Chip,Field,ActivityCard,ActivityRow} from '@/components/ui';
import {TasteprintShape} from '@/components/TasteprintShape';
import {useTheme} from '@/theme';
import {useAppStore} from '@/stores/app';
import {useUIStore} from '@/stores/ui';
import {catalog} from '@/repositories';
import {calculateTaste,calculateConfidence,tasteEvidence} from '@/services/engine';
import {matchScore} from '@/services/discovery';

export default function Home(){
 const{colors}=useTheme();
 const[why,setWhy]=useState(false),[campusSheet,setCampusSheet]=useState(false),[travelDraft,setTravelDraft]=useState('Chicago');
 const moves=useAppStore(s=>s.moves),campus=useAppStore(s=>s.campus),setCampus=useAppStore(s=>s.setCampus),travelCity=useAppStore(s=>s.travelCity),setTravelCity=useAppStore(s=>s.setTravelCity),saved=useAppStore(s=>s.savedIds),toggleSave=useAppStore(s=>s.toggleSave),friday=useAppStore(s=>s.fridayMode);
 const showToast=useUIStore(s=>s.showToast);
 const all=catalog.activities(),activity=catalog.activity(travelCity?'chicago':'bouldering')!,taste=calculateTaste(moves,all),confidence=calculateConfidence(moves.filter(m=>m.rank!==undefined).length),evidence=tasteEvidence(moves,all);
 const latest=moves.find(m=>m.id.startsWith('move-'))??moves[0];
 const photoQueue=moves.filter(m=>m.userId==='shawn'&&m.photo&&!m.ratings);
 return <Screen>
  <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}>
   <Brand size={38}/>
   <IconButton name="bell" label="Notifications" onPress={()=>router.push('/notifications')}/>
  </View>
  <Pressable accessibilityRole="button" accessibilityLabel="Change home or travel city" onPress={()=>setCampusSheet(true)} style={{alignSelf:'flex-start',flexDirection:'row',gap:8,alignItems:'center',minHeight:40,paddingHorizontal:12,borderRadius:14,backgroundColor:travelCity?colors.accentSoft:colors.surfaceAlt}}><Feather name={travelCity?'navigation':'map-pin'} size={15} color={travelCity?colors.accentPressed:colors.textSecondary}/><T variant="small">{travelCity?`Traveling · ${travelCity}`:campus}</T><Feather name="chevron-down" size={14} color={colors.textSecondary}/></Pressable>
  <View style={{gap:7}}><T variant="title">{travelCity?`Hey ${travelCity}. Meet Shawn.`:friday?'So… what’s the move?':'Good evening, Shawn'}</T><T color={colors.textSecondary}>{travelCity?'Your taste travels. These picks already feel like you.':friday?'Find something everyone will actually want to do.':'Here’s what’s worth doing tonight.'}</T></View>
  {photoQueue.length>0&&<Pressable accessibilityRole="button" accessibilityLabel={`${photoQueue.length} photos ready to rate`} onPress={()=>router.push('/queue')} style={{backgroundColor:colors.ink,borderRadius:22,padding:18,flexDirection:'row',alignItems:'center',gap:15}}><View style={{flexDirection:'row',width:74}}>{photoQueue.slice(0,3).map((move,index)=><View key={move.id} style={{position:index?'absolute':'relative',left:index*20,zIndex:3-index}}><Photo image={move.photo!} style={{width:46,height:58,borderRadius:12,borderWidth:2,borderColor:colors.ink}}/></View>)}</View><View style={{flex:1,gap:3}}><T variant="caption" color={colors.accent}>YOUR PHOTO QUEUE</T><T variant="heading" color={colors.white}>{photoQueue.length} moments to rate</T><T variant="small" color={colors.white}>Add the feeling, then tag the friends.</T></View><Feather name="arrow-right" size={20} color={colors.white}/></Pressable>}
  {friday&&<View style={{flexDirection:'row',gap:10}}><Button title="With a crew" icon="users" onPress={()=>router.navigate('/(tabs)/crews')} style={{flex:1}}/><Button title="Just me" variant="secondary" onPress={()=>router.navigate('/(tabs)/explore')} style={{flex:1}}/></View>}
  <Photo image={activity.image} style={{height:352,borderRadius:26}}>
   <LinearGradient colors={['rgba(12,16,10,0.05)','rgba(12,16,10,0.03)','rgba(12,16,10,0.93)']} locations={[0,.35,1]} style={{flex:1,padding:20,justifyContent:'space-between'}}>
    <View style={{alignSelf:'flex-start',backgroundColor:colors.background,paddingHorizontal:12,paddingVertical:7,borderRadius:12,flexDirection:'row',gap:7,alignItems:'center'}}><Feather name={travelCity?'map':'compass'} size={14} color={colors.accentPressed}/><T variant="caption" style={{fontWeight:'600'}} color={colors.ink}>{travelCity?`TASTE-MATCHED IN ${travelCity.toUpperCase()}`:'PICKED FOR YOU'}</T></View>
    <View style={{gap:7}}>
     <Pressable accessibilityRole="button" accessibilityLabel={`View ${activity.name}`} onPress={()=>router.push(`/activity/${activity.id}`)}><T variant="title" color={colors.white}>{activity.name}</T><T color={colors.white}>{travelCity?`${travelCity} · a first-day fit`:activity.placeName}</T></Pressable>
     <View style={{flexDirection:'row',gap:6,alignItems:'center'}}><Feather name="check-circle" size={15} color="#D3E7A0"/><T variant="label" color="#D3E7A0">{matchScore(taste,activity)}% your kind of move</T></View>
     <T variant="small" color={colors.white}>A little challenge. A good crew. Your kind of night.</T>
     <View style={{flexDirection:'row',gap:10,marginTop:7}}>
      <Pressable accessibilityRole="button" accessibilityLabel={saved.includes(activity.id)?`Unsave ${activity.name}`:`Save ${activity.name}`} onPress={()=>{toggleSave(activity.id);showToast(saved.includes(activity.id)?'Removed from Want to Try':'Saved to Want to Try');}} style={{minHeight:43,borderRadius:13,backgroundColor:colors.background,flex:1,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center'}}><Feather name={saved.includes(activity.id)?'check':'bookmark'} size={16} color={colors.ink}/><T variant="label" color={colors.ink}>{saved.includes(activity.id)?'Saved':'Save'}</T></Pressable>
      <Pressable accessibilityRole="button" onPress={()=>setWhy(true)} style={{minHeight:43,borderRadius:13,backgroundColor:'rgba(255,255,255,.23)',flex:1,alignItems:'center',justifyContent:'center'}}><T variant="label" color={colors.white}>Why this?</T></Pressable>
     </View>
    </View>
   </LinearGradient>
  </Photo>
  <View style={{gap:12}}><Section title="Tonight with your people" action="Plan one" onAction={()=>router.push('/crew/boys/recommend')}/><Pressable accessibilityRole="button" accessibilityLabel="Plan Friday after dark with The Boys" onPress={()=>router.push('/crew/boys/recommend')} style={{backgroundColor:colors.surface,borderRadius:22,overflow:'hidden'}}><Photo image="concert" style={{height:178,borderRadius:0}}><LinearGradient colors={['transparent','rgba(15,14,13,.84)']} style={{flex:1,justifyContent:'flex-end',padding:18,gap:8}}><View style={{alignSelf:'flex-start',backgroundColor:colors.accent,borderRadius:10,paddingHorizontal:10,paddingVertical:6}}><T variant="caption" color={colors.ink}>FRI · 8:30 PM</T></View><T variant="heading" color="#fff">Friday after dark</T><View style={{flexDirection:'row',alignItems:'center',gap:10}}><AvatarStack ids={['shawn','alex','ryan','noah']} size={28}/><T variant="small" color="#fff">The Boys · 3 interested</T></View></LinearGradient></Photo><View style={{padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View><T variant="label">No plan yet. That’s the fun part.</T><T variant="caption" color={colors.textSecondary}>Let everyone vote, then lock it in.</T></View><Feather name="chevron-right" size={19} color={colors.textSecondary}/></View></Pressable></View>
  <View style={{gap:12}}>
   <Section title="From your people" action="See all" onAction={()=>router.push('/profile/maya')}/>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:19}}>{['maya','alex','ryan','noah'].map(id=><Pressable key={id} accessibilityRole="button" accessibilityLabel={'View '+catalog.user(id)?.displayName} onPress={()=>router.push({pathname:'/profile/[username]',params:{username:catalog.user(id)?.username??id}})} style={{alignItems:'center',gap:5}}><Avatar userId={id} size={49}/><T variant="caption" color={colors.textSecondary}>{catalog.user(id)?.displayName.split(' ')[0]}</T></Pressable>)}</ScrollView>
   <Pressable accessibilityRole="button" accessibilityLabel="Maya's number one Active move" onPress={()=>router.push('/profile/maya')} style={{backgroundColor:colors.surface,padding:14,borderRadius:18,flexDirection:'row',gap:12,alignItems:'center'}}><Avatar userId="maya" size={38}/><View style={{flex:1,gap:2}}><T variant="caption" color={colors.textSecondary}>Maya found a new favorite</T><T variant="label">Bouldering <T variant="caption" color={colors.success}> · #1 in Active</T></T><T variant="caption" color={colors.muted}>A little outside your usual. In the best way.</T></View><Feather name="chevron-right" size={17} color={colors.textSecondary}/></Pressable>
  </View>
  <View style={{gap:14}}><Section title={travelCity?`Your energy in ${travelCity}`:'Around '+campus} action="Explore" onAction={()=>router.navigate('/(tabs)/explore')}/><View style={{flexDirection:'row',gap:14}}>{(travelCity?['thrift','jazz']:['shawarma','picnic']).map(id=>{const a=catalog.activity(id)!;return <ActivityCard key={id} activity={a} compact match={matchScore(taste,a)} subtitle={travelCity?`${travelCity} · picked for you`:undefined} meta={travelCity?'Nearby now':undefined}/>;})}</View></View>
  <Pressable accessibilityRole="button" accessibilityLabel="See your Tasteprint" onPress={()=>router.push('/taste')} style={{backgroundColor:colors.surfaceAlt,borderRadius:22,padding:20,flexDirection:'row',alignItems:'center',gap:6}}><View style={{flex:1,gap:6}}><T variant="caption" color={colors.textSecondary} style={{letterSpacing:1}}>YOUR TASTE, TAKING SHAPE</T><T variant="heading">A little more you.</T><T variant="small" color={colors.textSecondary}>{confidence}% calibrated. Every ranked Move tells us more.</T></View><TasteprintShape vector={taste} size={95}/></Pressable>
  {latest&&<View style={{gap:12}}><Section title="Your latest Move"/><ActivityRow activity={catalog.activity(latest.activityId)!} subtitle={latest.rank?'#'+latest.rank+' in '+latest.category+' · View your memory':'Ready when you are. Give it a rank.'} onPress={()=>router.push({pathname:'/move/[id]',params:{id:latest.id}})}/></View>}
  <View style={{alignItems:'center',paddingTop:8,gap:6}}><AvatarStack ids={['shawn','alex','ryan','noah']} size={26}/><T variant="caption" color={colors.muted}>Real life hits different together.</T></View>
  <Sheet visible={why} onClose={()=>setWhy(false)} title={`Why ${activity.name}?`}><TasteprintShape vector={taste} size={160}/><T>{travelCity?`It carries your usual mix of novelty, movement, and social energy into ${travelCity}.`:'It brings together movement, a little novelty, and time with your people.'}</T>{evidence.slice(0,2).map(e=><View key={e.axis} style={{flexDirection:'row',gap:10}}><Feather name="check-circle" size={18} color={colors.success}/><T variant="small" style={{flex:1}}>{e.message}</T></View>)}<T variant="caption" color={colors.textSecondary}>Your match is based on your ranked Moves. Your taste will keep changing.</T><Button title="Take a closer look" onPress={()=>{setWhy(false);router.push(`/activity/${activity.id}`);}}/></Sheet>
  <Sheet visible={campusSheet} onClose={()=>setCampusSheet(false)} title="Where are you moving through?"><T color={colors.textSecondary}>Use home mode for everyday picks or tell WTM where you landed. Your ranked taste stays the same.</T><Chip label="Home · UIUC" selected={!travelCity} icon="home" onPress={()=>{setCampus('UIUC');setTravelCity(null);setCampusSheet(false);}}/><View style={{gap:10}}><T variant="label">I’m in a new city</T><Field value={travelDraft} onChangeText={setTravelDraft} placeholder="City" accessibilityLabel="Travel city" /><View style={{flexDirection:'row',gap:8}}>{['Chicago','New York','Austin'].map(city=><Chip key={city} label={city} selected={travelDraft===city} onPress={()=>setTravelDraft(city)}/>)}</View><Button title="Use travel mode" icon="navigation" disabled={!travelDraft.trim()} onPress={()=>{setTravelCity(travelDraft);setCampusSheet(false);showToast(`Finding your kind of places in ${travelDraft}.`);}}/></View><Button title="Explore all moves" variant="secondary" onPress={()=>{setCampusSheet(false);router.navigate('/(tabs)/explore');}}/></Sheet>
 </Screen>;
}
